# k3d cluster configuration to run Kubernetes on Docker with exposed ingress ports
apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: saga
servers: 1
agents: 1
# Expose HTTP/HTTPS for the arch.homework ingress via the k3d load balancer
ports:
  - port: 80:80@loadbalancer
  - port: 443:443@loadbalancer
